# Generated by Django 5.1.2 on 2024-10-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasemodel',
            name='username',
            field=models.CharField(blank=True, max_length=32, verbose_name='username'),
        ),
    ]
