# Generated by Django 5.1.2 on 2024-10-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_userbasemodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasemodel',
            name='email',
        ),
    ]
